### PR TITLE
add image description to gallery image

### PR DESCRIPTION
**Pull request by ciotto**

### CODE REVIEW

**Comment by ghost** [comment]
Hi Ciotto, is there any way of adding the image titles to the description aswell?

**Comment by ciotto** [comment]
Hi,
you need to get title ($title = get_post( $attachment_id_item )->post_title;) and add it as attribute (data-img-title=\"{$title}\") in content-ds-gallery.php at line 146.
After that, you add the title (title = currItem.attr('data-img-title'),) in jquery.slider-pack.js at line 2032.

Have fun.

**Comment by ghost** [comment]
Grazie mille Christian

I obviously need to learn more jquery, i will get on it tommorow. You have saved my day.

Ciao

Harry

Connected by Motorola

**Comment by ghost** [comment]
Hi Christian

I have tried those changes, but unfortunately, if I add the changes to jquery.slider-pack.js, nothing happens at all and if I make them instead to the minified version, I get the titles, but they start to repeat themselves after three titles.I cannot think why this would be, very strange behaviour. Do you have any ideas why this might be happening? Also I have changed the functions.php to call the non minified version now which brings in the titles, but again they are repeating. Sorry about this any help is very much appreciated.

**Comment by bszen27** [comment]
@ciotto:

Okay, so I have been looking at your code in jquery.slider.pack.js for days and I believe I have narrowed down the problem. If you closely look at the variable currQueueItem in the function _loadNextImage (line 2002), you will see that there are THREE different items being loaded. So this seems to imply that the function is being used three times by the code, which is throwing things off in terms of the descriptions.  For example, if you have more than 3 items in a gallery, you will notice that the descriptions for images 1 through 3 will start to repeat and show as the descriptions for image #4-#6, #7-#9, etc. Could you verify this behavior first with your own installation, so I know I am not losing my mind?

I know there are a few pieces of code in there that I am not entirely sure of, so it is obviously possible you coded against this already and something went astray. I am creating a site for a client who wants the descriptions, so the point of this is just to get it working correctly. Thank you.

**Comment by ciotto** [comment]
Hi, actually I also have this problem. The gallery creates three blocks in which they are draw for three photos at a time to avoid loading problem. I think we need to find the point where it is recharged. unfortunately my mac is broken so I can not verify. I will verify as soon as possible.

**Comment by ritademolfetta** [comment]
@ciotto 
Hi! Is it possible to put both title and description of an image in the box in which there are title and description of an album?

Thank you

**Comment by ciotto** [comment]
Hi @ritademolfetta,
if you want to move top box on bottom you can do this with css (two-dim-slider.less, remember to delete the created css file in the "uploads/wp-less" folder) otherwise if you want to put image title and description in bottom box you can modify the js file (jquery.slider-pack.1.1.min.js, not minified file is jquery.slider-pack.1.1.js)

Good luck

**Comment by ritademolfetta** [comment]
@ciotto so I have to modify the minified file, right?

I trying to do this since yesterday.
I changed '.block-inside' with '.album-content' in the following function [ o.appendTo(i.find(".block-inside")) ] but actually it is not working...

Can you help me?

thank you

**Comment by ritademolfetta** [comment]
@ciotto 
Is it possible to know:
1) which is the function that update info in the album description box?
2) how can I update the .album-content run time??

**Comment by ciotto** [comment]
Good question @ritademolfetta,
the `_showAlbumInfo()` function update the album info but at this point there aren't image data. You can update _.album-content_ in `_updateCurrItemId()` function using this code lines:

``` javascript
var item = items.eq(id),
    title =item.attr('data-img-title'),
    desc = item.attr('data-img-desc');

    //$('.album-name-indicator').text(title);
    //$('.album-title').text(title);
    $('.album-content').text(desc);
```

**Comment by ritademolfetta** [comment]
@ciotto thank you a lot for your support!

**Comment by ritademolfetta** [comment]
Hi @ciotto ! 

I edited the both javascript files, minified one and not minified one.

```
_updateCurrItemId:function(albumId,id) {
        [...]

            self.currItemId = id;

            var item = items.eq(id),
                //title =item.attr('data-img-title'),
                desc = item.attr('data-img-desc');

                //$('.album-name-indicator').text(title);
                //$('.album-title').text(title);
                $('.album-content').text(desc);


        } else {
            alert('Album is empty:'+ albumId+' id:'+ id);
        }
    },

[...] n.currItemId=t; var item=i.eq(t),desc = item.attr("data-img-desc"); jQuery(".album-content").text(desc); [...]
```

There are some bugs:

1) When I open web site at the first time, the description of the first photo doesn't show. 
    In this case I tried to modify function _getItem but still it is not working!

2)  I have two albums: first album contain one photo, second album contain two photos. 
    I navigate between two albums (up/down).
        > currentAlbum = 1, currentImg = 1 
        > click DOWN of my keyboard
        > currentAlbum = 2, currentImg = 1 
        > currentAlbum = 2, currentImg = 2
        > click UP of my keyboard
        > currentAlbum = 1, currentImg = 1 
        > click DOWN of my keyboard
        > currentAlbum = 2, currentImg = 2 --> the description correspond to first photo's one
    In this case I tried to change function _moveTo but still it is not working!

My problem is: I haven't the right tools to test and to do the debuggs! 
Thank you!

**Comment by ciotto** [comment]
Hi @ritademolfetta,

1) you can fix this by replacing `self._albumNameIndicator.text( self.albumsArr[self.currAlbumId].find('.album-title').text() );` with 
`self._updateCurrItemId(self.currAlbumId, self.currItemId);` in __updateControls_ function

2) you can fix this by replacing `self._updateCurrItemId(self.currAlbumId-1, 0);` with `self._updateCurrItemId(self.currAlbumId-1, -1);` in __moveTo_ function and by adding `if(id == -1) id = numItems - 1;` in __updateCurrItemId_ function.

Google Chrome have all you need for debugging ([documentation](https://developer.chrome.com/devtools/docs/javascript-debugging)), but also other browsers have similar tools.

**Comment by danielkoch** [comment]
@bszen27 and @ciotto: Is the issue with the three items fixed? In my installation (with the latests master-touchfolio-theme) the fourth element gets the description of the first item...

**Comment by ghost** [comment]
Hi Daniel

I did fix this in the end, with everyone's help, i'll have a look for you when I return home.

Harry

On Thursday, 11 September 2014, 13:05, Daniel Koch notifications@github.com wrote:

@bszen27 and @ciotto: Is the issue with the three items fixed? In my installation (with the latests master-touchfolio-theme) the fourth element gets the description of the first item...

**Comment by Moolfreet** [comment]
Same “three items” issue in my local Mamp installation with the latest master-touchfolio-theme. Hope for a fix, to use it on a production website.

**Comment by ciotto** [comment]
Hi,
I checked my dev branch and I found some missing features in the master branch, so I merge master into dev and I created a pull-request.

**Comment by danielkoch** [comment]
I created a new issue #48 for the "only three image descriptions are possible" bug.

**Comment by ghost** [comment]
Hi daniel, do you want me to send over my files? 

Connected by Motorola

**Comment by danielkoch** [comment]
@harryrook sure, would be great. If your version work we could try to fix it in a fork an do a pull-request.

**Comment by ghost** [comment]
Hi Daniel

Here is the site, just double check it is doing what you want before I send it: http://peterarscott.com/

On Saturday, 13 September 2014, 12:10, Daniel Koch notifications@github.com wrote:

@harryrook shure, would be great. If your version work we could try to fix it in a fork an do a pull-request.

**Comment by danielkoch** [comment]
@harryrook: Yes that is it. I think this version works also with album description?!

**Comment by ghost** [comment]
Ok cool, give me a while I have so many different folders, will have to work out which is the correct one. I'm not sure it works with album description though, that may have been cut out, when Ciotto was helping me. Ha think I found it easier than expected, try this one out and let me know how it goes.

Harry

On Saturday, 13 September 2014, 13:13, Daniel Koch notifications@github.com wrote:

@harryrook: Yes that is it. I think this version works also with album description?!

**Comment by danielkoch** [comment]
@harryrook: I fixed my issue #48. The pull-request contains only the fix for the description because actually this is the only image meta information in the current Touchfolio master.

**Pull request merged**
